#! /bin/bash
#######################################################################
### Set case parameters
### user: User
### jobn: The name of the output file in data directory
### pnum: Project number for charging/allocation purposes
### rnam: The name of the run
### rtyp: The queue to submit
### tihh: Time to run (hours)
### timm: Time to run (minutes)
### nnds: Number of nodes to run on
### rund: Name of the run directory where data are placed
### runo: Standard output filename
### dirm: Location of the submit script and output directory
### csrc: Directory containing code source

user=mmcguinn
jobn=ncarles
pnum=UCUB0079
rnam=testcase
rtyp=regular
tihh=0
timm=10
nnds=1
runo=logfile.out
rund=CHECK


###############################################
### CREATE PBS SCRIPTS FOR ANALYSIS AND RUN ###
###############################################
cd $rund

# EXECUTE SCRIPT
cat > EXEC_STEP << EXEC
#!/bin/sh
#PBS -N $rund
#PBS -l walltime=$tihh:$timm:00
#PBS -l select=$nnds:ncpus=32:mpiprocs=32
#PBS -A $pnum
#PBS -q $rtyp
#PBS -o exec.out
#PBS -e exec.err

module purge
module load intel/17.0.1
module load impi

mpirun ./lesmpi > $runo
EXEC


echo '--------------------------------------'
echo '             Execute Step             '
echo '--------------------------------------'

echo '---> Running' $rund
qsub < EXEC_STEP
echo ''
