SUBROUTINE set_paths
! SET FILE PATH FOR RESTART AND DIRECTORIES FOR SAVING, HISTORY, AND VIZ FILES

  USE pars

  path_res='./data/u.mp.30L00005' ! PATH AND FILE NAME OF VELOCITY RESTART FILE

  path_sav    = './data'    ! PATH WHERE THE NEW 3D VOLUMES ARE TO BE SAVED
  path_his    = './data'    ! PATH WHERE THE NEW HISTORY FILES ARE TO BE SAVED
  path_viz_xy = './data'    ! PATH WHERE XY DATA PLANES ARE TO BE SAVED
  path_viz_xz = './data'    ! PATH WHERE XZ DATA PLANES ARE TO BE SAVED
  path_viz_yz = './data'    ! PATH WHERE YZ DATA PLANES ARE TO BE SAVED
  path_stuf   = './data'    ! PATH WHERE INFO ABOUT VIZ PLANES ARE TO BE SAVED

  RETURN
END SUBROUTINE
