!     SUBROUTINE COSQF(N,X,WSAVE)
!
!     SUBROUTINE COSQF COMPUTES THE FAST FOURIER TRANSFORM OF QUARTER
!     WAVE DATA. THAT IS , COSQF COMPUTES THE COEFFICIENTS IN A COSINE
!     SERIES REPRESENTATION WITH ONLY ODD WAVE NUMBERS. THE TRANSFORM
!     IS DEFINED BELOW AT OUTPUT PARAMETER X
!
!     COSQF IS THE UNNORMALIZED INVERSE OF COSQB SINCE A CALL OF COSQF
!     FOLLOWED BY A CALL OF COSQB WILL MULTIPLY THE INPUT SEQUENCE X
!     BY 4*N.
!
!     THE ARRAY WSAVE WHICH IS USED BY SUBROUTINE COSQF MUST BE
!     INITIALIZED BY CALLING SUBROUTINE COSQI(N,WSAVE).
!
!
!     INPUT PARAMETERS
!
!     N       THE LENGTH OF THE ARRAY X TO BE TRANSFORMED.  THE METHOD
!             IS MOST EFFICIENT WHEN N IS A PRODUCT OF SMALL PRIMES.
!
!     X       AN ARRAY WHICH CONTAINS THE SEQUENCE TO BE TRANSFORMED
!
!     WSAVE   A WORK ARRAY WHICH MUST BE DIMENSIONED AT LEAST 3*N+15
!             IN THE PROGRAM THAT CALLS COSQF. THE WSAVE ARRAY MUST BE
!             INITIALIZED BY CALLING SUBROUTINE COSQI(N,WSAVE) AND A
!             DIFFERENT WSAVE ARRAY MUST BE USED FOR EACH DIFFERENT
!             VALUE OF N. THIS INITIALIZATION DOES NOT HAVE TO BE
!             REPEATED SO LONG AS N REMAINS UNCHANGED THUS SUBSEQUENT
!             TRANSFORMS CAN BE OBTAINED FASTER THAN THE FIRST.
!
!     OUTPUT PARAMETERS
!
!     X       FOR I=1,...,N
!
!                  X(I) = X(1) PLUS THE SUM FROM K=2 TO K=N OF
!
!                     2*X(K)*COS((2*I-1)*(K-1)*PI/(2*N))
!
!                  A CALL OF COSQF FOLLOWED BY A CALL OF
!                  COSQB WILL MULTIPLY THE SEQUENCE X BY 4*N.
!                  THEREFORE COSQB IS THE UNNORMALIZED INVERSE
!                  OF COSQF.
!
!     WSAVE   CONTAINS INITIALIZATION CALCULATIONS WHICH MUST NOT
!             BE DESTROYED BETWEEN CALLS OF COSQF OR COSQB.
!
SUBROUTINE cosqf (N,X,WSAVE)

    DIMENSION X(*), WSAVE(*)

    DATA SQRT2 /1.4142135623731/

  IF (N-2 .LT. 0) THEN
    CONTINUE
  ELSE IF (N-2 .EQ. 0) THEN
    TSQX = SQRT2*X(2)
    X(2) = X(1)-TSQX
    X(1) = X(1)+TSQX
  ELSE !(N-2 .GT. 0)
    CALL cosqf1 (N,X,WSAVE,WSAVE(N+1))
  END IF

RETURN
END SUBROUTINE cosqf
