!     SUBROUTINE SINQI(N,WSAVE)
!
!     SUBROUTINE SINQI INITIALIZES THE ARRAY WSAVE WHICH IS USED IN
!     BOTH SINQF AND SINQB. THE PRIME FACTORIZATION OF N TOGETHER WITH
!     A TABULATION OF THE TRIGONOMETRIC FUNCTIONS ARE COMPUTED AND
!     STORED IN WSAVE.
!
!     INPUT PARAMETER
!
!     N       THE LENGTH OF THE SEQUENCE TO BE TRANSFORMED. THE METHOD
!             IS MOST EFFICIENT WHEN N IS A PRODUCT OF SMALL PRIMES.
!
!     OUTPUT PARAMETER
!
!     WSAVE   A WORK ARRAY WHICH MUST BE DIMENSIONED AT LEAST 3*N+15.
!             THE SAME WORK ARRAY CAN BE USED FOR BOTH SINQF AND SINQB
!             AS LONG AS N REMAINS UNCHANGED. DIFFERENT WSAVE ARRAYS
!             ARE REQUIRED FOR DIFFERENT VALUES OF N. THE CONTENTS OF
!             WSAVE MUST NOT BE CHANGED BETWEEN CALLS OF SINQF OR SINQB.
!
SUBROUTINE sinqi (N,WSAVE)

    DIMENSION WSAVE(*)

  CALL cosqi (N,WSAVE)

RETURN
END SUBROUTINE sinqi
