!     SUBROUTINE SINTI(N,WSAVE)
!
!     SUBROUTINE SINTI INITIALIZES THE ARRAY WSAVE WHICH IS USED IN
!     SUBROUTINE SINT. THE PRIME FACTORIZATION OF N TOGETHER WITH
!     A TABULATION OF THE TRIGONOMETRIC FUNCTIONS ARE COMPUTED AND
!     STORED IN WSAVE.
!
!     INPUT PARAMETER
!
!     N       THE LENGTH OF THE SEQUENCE TO BE TRANSFORMED.  THE METHOD
!             IS MOST EFFICIENT WHEN N+1 IS A PRODUCT OF SMALL PRIMES.
!
!     OUTPUT PARAMETER
!
!     WSAVE   A WORK ARRAY WITH AT LEAST INT(2.5*N+15) LOCATIONS.
!             DIFFERENT WSAVE ARRAYS ARE REQUIRED FOR DIFFERENT VALUES
!             OF N. THE CONTENTS OF WSAVE MUST NOT BE CHANGED BETWEEN
!             CALLS OF SINT.
!
SUBROUTINE sinti (N,WSAVE)

    DIMENSION WSAVE(*)

  PI = PIMACH(DUM)
  IF (N .LE. 1) THEN
    CONTINUE
  ELSE
    NS2 = N/2
    NP1 = N+1
    DT = PI/FLOAT(NP1)
    DO K=1,NS2
      WSAVE(K) = 2.*SIN(K*DT)
    END DO
    CALL rffti (NP1,WSAVE(NS2+1))
  END IF

RETURN
END SUBROUTINE sinti
