!     SUBROUTINE CFFTB(N,C,WSAVE)
!
!     SUBROUTINE CFFTB COMPUTES THE BACKWARD COMPLEX DISCRETE FOURIER
!     TRANSFORM (THE FOURIER SYNTHESIS). EQUIVALENTLY , CFFTB COMPUTES
!     A COMPLEX PERIODIC SEQUENCE FROM ITS FOURIER COEFFICIENTS.
!     THE TRANSFORM IS DEFINED BELOW AT OUTPUT PARAMETER C.
!
!     A CALL OF CFFTF FOLLOWED BY A CALL OF CFFTB WILL MULTIPLY THE
!     SEQUENCE BY N.
!
!     THE ARRAY WSAVE WHICH IS USED BY SUBROUTINE CFFTB MUST BE
!     INITIALIZED BY CALLING SUBROUTINE CFFTI(N,WSAVE).
!
!     INPUT PARAMETERS
!
!
!     N      THE LENGTH OF THE COMPLEX SEQUENCE C. THE METHOD IS
!            MORE EFFICIENT WHEN N IS THE PRODUCT OF SMALL PRIMES.
!
!     C      A COMPLEX ARRAY OF LENGTH N WHICH CONTAINS THE SEQUENCE
!
!     WSAVE   A REAL WORK ARRAY WHICH MUST BE DIMENSIONED AT LEAST 4N+15
!             IN THE PROGRAM THAT CALLS CFFTB. THE WSAVE ARRAY MUST BE
!             INITIALIZED BY CALLING SUBROUTINE CFFTI(N,WSAVE) AND A
!             DIFFERENT WSAVE ARRAY MUST BE USED FOR EACH DIFFERENT
!             VALUE OF N. THIS INITIALIZATION DOES NOT HAVE TO BE
!             REPEATED SO LONG AS N REMAINS UNCHANGED THUS SUBSEQUENT
!             TRANSFORMS CAN BE OBTAINED FASTER THAN THE FIRST.
!             THE SAME WSAVE ARRAY CAN BE USED BY CFFTF AND CFFTB.
!
!     OUTPUT PARAMETERS
!
!     C      FOR J=1,...,N
!
!                C(J)=THE SUM FROM K=1,...,N OF
!
!                      C(K)*EXP(I*(J-1)*(K-1)*2*PI/N)
!
!                            WHERE I=SQRT(-1)
!
!     WSAVE   CONTAINS INITIALIZATION CALCULATIONS WHICH MUST NOT BE
!             DESTROYED BETWEEN CALLS OF SUBROUTINE CFFTF OR CFFTB
!
SUBROUTINE cfftb (N,C,WSAVE)

    DIMENSION C(*), WSAVE(*)

  IF (N .EQ. 1) THEN
    CONTINUE
  ELSE
    IW1 = N+N+1
    IW2 = IW1+N+N
    CALL cfftb1 (N,C,WSAVE,WSAVE(IW1),WSAVE(IW2))
  END IF

RETURN
END SUBROUTINE cfftb
