!     SUBROUTINE COSQB(N,X,WSAVE)
!
!     SUBROUTINE COSQB COMPUTES THE FAST FOURIER TRANSFORM OF QUARTER
!     WAVE DATA. THAT IS , COSQB COMPUTES A SEQUENCE FROM ITS
!     REPRESENTATION IN TERMS OF A COSINE SERIES WITH ODD WAVE NUMBERS.
!     THE TRANSFORM IS DEFINED BELOW AT OUTPUT PARAMETER X.
!
!     COSQB IS THE UNNORMALIZED INVERSE OF COSQF SINCE A CALL OF COSQB
!     FOLLOWED BY A CALL OF COSQF WILL MULTIPLY THE INPUT SEQUENCE X
!     BY 4*N.
!
!     THE ARRAY WSAVE WHICH IS USED BY SUBROUTINE COSQB MUST BE
!     INITIALIZED BY CALLING SUBROUTINE COSQI(N,WSAVE).
!
!
!     INPUT PARAMETERS
!
!     N       THE LENGTH OF THE ARRAY X TO BE TRANSFORMED.  THE METHOD
!             IS MOST EFFICIENT WHEN N IS A PRODUCT OF SMALL PRIMES.
!
!     X       AN ARRAY WHICH CONTAINS THE SEQUENCE TO BE TRANSFORMED
!
!     WSAVE   A WORK ARRAY THAT MUST BE DIMENSIONED AT LEAST 3*N+15
!             IN THE PROGRAM THAT CALLS COSQB. THE WSAVE ARRAY MUST BE
!             INITIALIZED BY CALLING SUBROUTINE COSQI(N,WSAVE) AND A
!             DIFFERENT WSAVE ARRAY MUST BE USED FOR EACH DIFFERENT
!             VALUE OF N. THIS INITIALIZATION DOES NOT HAVE TO BE
!             REPEATED SO LONG AS N REMAINS UNCHANGED THUS SUBSEQUENT
!             TRANSFORMS CAN BE OBTAINED FASTER THAN THE FIRST.
!
!     OUTPUT PARAMETERS
!
!     X       FOR I=1,...,N
!
!                  X(I)= THE SUM FROM K=1 TO K=N OF
!
!                    4*X(K)*COS((2*K-1)*(I-1)*PI/(2*N))
!
!                  A CALL OF COSQB FOLLOWED BY A CALL OF
!                  COSQF WILL MULTIPLY THE SEQUENCE X BY 4*N.
!                  THEREFORE COSQF IS THE UNNORMALIZED INVERSE
!                  OF COSQB.
!
!     WSAVE   CONTAINS INITIALIZATION CALCULATIONS WHICH MUST NOT
!             BE DESTROYED BETWEEN CALLS OF COSQB OR COSQF.
!
SUBROUTINE cosqb (N,X,WSAVE)

      DIMENSION X(*), WSAVE(*)

      DATA TSQRT2 /2.82842712474619/

  IF (N-2 .LT. 0) THEN
    X(1) = 4.*X(1)
  ELSE IF (N-2 .EQ. 0) THEN
    X1 = 4.*(X(1)+X(2))
    X(2) = TSQRT2*(X(1)-X(2))
    X(1) = X1
  ELSE !(N-2 .GT 0)
    CALL cosqb1 (N,X,WSAVE,WSAVE(N+1))
  END IF

RETURN
END SUBROUTINE cosqb
