!     SUBROUTINE  EZFFTI(N,WSAVE)
!
!     SUBROUTINE EZFFTI INITIALIZES THE ARRAY WSAVE WHICH IS USED IN
!     BOTH EZFFTF AND EZFFTB. THE PRIME FACTORIZATION OF N TOGETHER WITH
!     A TABULATION OF THE TRIGONOMETRIC FUNCTIONS ARE COMPUTED AND
!     STORED IN WSAVE.
!
!     INPUT PARAMETER
!
!     N       THE LENGTH OF THE SEQUENCE TO BE TRANSFORMED.
!
!     OUTPUT PARAMETER
!
!     WSAVE   A WORK ARRAY WHICH MUST BE DIMENSIONED AT LEAST 3*N+15.
!             THE SAME WORK ARRAY CAN BE USED FOR BOTH EZFFTF AND EZFFTB
!             AS LONG AS N REMAINS UNCHANGED. DIFFERENT WSAVE ARRAYS
!             ARE REQUIRED FOR DIFFERENT VALUES OF N.
!
SUBROUTINE ezffti (N,WSAVE)

    DIMENSION WSAVE(*)

  IF (N .EQ. 1) THEN
    CONTINUE
  ELSE
    CALL ezfft1 (N,WSAVE(2*N+1),WSAVE(3*N+1))
  END IF

RETURN
END SUBROUTINE ezffti
