!     SUBROUTINE SINT(N,X,WSAVE)
!
!     SUBROUTINE SINT COMPUTES THE DISCRETE FOURIER SINE TRANSFORM
!     OF AN ODD SEQUENCE X(I). THE TRANSFORM IS DEFINED BELOW AT
!     OUTPUT PARAMETER X.
!
!     SINT IS THE UNNORMALIZED INVERSE OF ITSELF SINCE A CALL OF SINT
!     FOLLOWED BY ANOTHER CALL OF SINT WILL MULTIPLY THE INPUT SEQUENCE
!     X BY 2*(N+1).
!
!     THE ARRAY WSAVE WHICH IS USED BY SUBROUTINE SINT MUST BE
!     INITIALIZED BY CALLING SUBROUTINE SINTI(N,WSAVE).
!
!     INPUT PARAMETERS
!
!     N       THE LENGTH OF THE SEQUENCE TO BE TRANSFORMED.  THE METHOD
!             IS MOST EFFICIENT WHEN N+1 IS THE PRODUCT OF SMALL PRIMES.
!
!     X       AN ARRAY WHICH CONTAINS THE SEQUENCE TO BE TRANSFORMED
!
!
!     WSAVE   A WORK ARRAY WITH DIMENSION AT LEAST INT(2.5*N+15)
!             IN THE PROGRAM THAT CALLS SINT. THE WSAVE ARRAY MUST BE
!             INITIALIZED BY CALLING SUBROUTINE SINTI(N,WSAVE) AND A
!             DIFFERENT WSAVE ARRAY MUST BE USED FOR EACH DIFFERENT
!             VALUE OF N. THIS INITIALIZATION DOES NOT HAVE TO BE
!             REPEATED SO LONG AS N REMAINS UNCHANGED THUS SUBSEQUENT
!             TRANSFORMS CAN BE OBTAINED FASTER THAN THE FIRST.
!
!     OUTPUT PARAMETERS
!
!     X       FOR I=1,...,N
!
!                  X(I)= THE SUM FROM K=1 TO K=N
!
!                       2*X(K)*SIN(K*I*PI/(N+1))
!
!                  A CALL OF SINT FOLLOWED BY ANOTHER CALL OF
!                  SINT WILL MULTIPLY THE SEQUENCE X BY 2*(N+1).
!                  HENCE SINT IS THE UNNORMALIZED INVERSE
!                  OF ITSELF.
!
!     WSAVE   CONTAINS INITIALIZATION CALCULATIONS WHICH MUST NOT BE
!             DESTROYED BETWEEN CALLS OF SINT.
!
SUBROUTINE sint (N,X,WSAVE)

    DIMENSION X(*), WSAVE(*)

  NP1 = N+1
  IW1 = N/2+1
  IW2 = IW1+NP1
  IW3 = IW2+NP1
  CALL sint1(N,X,WSAVE,WSAVE(IW1),WSAVE(IW2),WSAVE(IW3))

RETURN
END SUBROUTINE sint
